// Mocks generated by Mockito 5.4.6 from annotations
// in mali_app/test/domain/usecases/usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mali_app/domain/entities/budget.dart' as _i9;
import 'package:mali_app/domain/entities/exchange_rate.dart' as _i14;
import 'package:mali_app/domain/entities/goal_contribution.dart' as _i12;
import 'package:mali_app/domain/entities/savings_goal.dart' as _i11;
import 'package:mali_app/domain/entities/transaction.dart' as _i5;
import 'package:mali_app/domain/entities/wallet.dart' as _i7;
import 'package:mali_app/domain/repositories/budget_repository.dart' as _i8;
import 'package:mali_app/domain/repositories/exchange_rate_repository.dart'
    as _i13;
import 'package:mali_app/domain/repositories/goal_repository.dart' as _i10;
import 'package:mali_app/domain/repositories/transaction_repository.dart'
    as _i3;
import 'package:mali_app/domain/repositories/wallet_repository.dart' as _i6;
import 'package:mali_app/domain/usecases/sync_usecase.dart' as _i2;
import 'package:mali_app/domain/value_objects/currency_code.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePushResult_0 extends _i1.SmartFake implements _i2.PushResult {
  _FakePushResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePullResult_1 extends _i1.SmartFake implements _i2.PullResult {
  _FakePullResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionRepository extends _i1.Mock
    implements _i3.ITransactionRepository {
  @override
  _i4.Future<void> save(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#save, [transaction]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Transaction?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i4.Future<_i5.Transaction?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Transaction?>.value(),
          )
          as _i4.Future<_i5.Transaction?>);

  @override
  _i4.Future<_i5.Transaction?> findBySyncId(String? syncId) =>
      (super.noSuchMethod(
            Invocation.method(#findBySyncId, [syncId]),
            returnValue: _i4.Future<_i5.Transaction?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Transaction?>.value(),
          )
          as _i4.Future<_i5.Transaction?>);

  @override
  _i4.Future<List<_i5.Transaction>> list({
    required _i3.TransactionQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#list, [], {#query: query}),
            returnValue: _i4.Future<List<_i5.Transaction>>.value(
              <_i5.Transaction>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i5.Transaction>>.value(
              <_i5.Transaction>[],
            ),
          )
          as _i4.Future<List<_i5.Transaction>>);

  @override
  _i4.Stream<List<_i5.Transaction>> watchByWallet(String? walletId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByWallet, [walletId]),
            returnValue: _i4.Stream<List<_i5.Transaction>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i5.Transaction>>.empty(),
          )
          as _i4.Stream<List<_i5.Transaction>>);

  @override
  _i4.Future<List<_i5.Transaction>> listUnsynced() =>
      (super.noSuchMethod(
            Invocation.method(#listUnsynced, []),
            returnValue: _i4.Future<List<_i5.Transaction>>.value(
              <_i5.Transaction>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i5.Transaction>>.value(
              <_i5.Transaction>[],
            ),
          )
          as _i4.Future<List<_i5.Transaction>>);

  @override
  _i4.Future<void> softDelete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IWalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWalletRepository extends _i1.Mock implements _i6.IWalletRepository {
  @override
  _i4.Future<void> save(_i7.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#save, [wallet]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Wallet?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i4.Future<_i7.Wallet?>.value(),
            returnValueForMissingStub: _i4.Future<_i7.Wallet?>.value(),
          )
          as _i4.Future<_i7.Wallet?>);

  @override
  _i4.Stream<List<_i7.Wallet>> watchActive() =>
      (super.noSuchMethod(
            Invocation.method(#watchActive, []),
            returnValue: _i4.Stream<List<_i7.Wallet>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i7.Wallet>>.empty(),
          )
          as _i4.Stream<List<_i7.Wallet>>);

  @override
  _i4.Future<void> updateBalance({
    required String? walletId,
    required String? balance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalance, [], {
              #walletId: walletId,
              #balance: balance,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IBudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBudgetRepository extends _i1.Mock implements _i8.IBudgetRepository {
  @override
  _i4.Future<void> save(_i9.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#save, [budget]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.Budget>> watchMonthBudgets({
    required int? year,
    required int? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthBudgets, [], {
              #year: year,
              #month: month,
            }),
            returnValue: _i4.Stream<List<_i9.Budget>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i9.Budget>>.empty(),
          )
          as _i4.Stream<List<_i9.Budget>>);

  @override
  _i4.Future<void> updateSpentAmount({
    required String? budgetId,
    required String? spentAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpentAmount, [], {
              #budgetId: budgetId,
              #spentAmount: spentAmount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IGoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGoalRepository extends _i1.Mock implements _i10.IGoalRepository {
  @override
  _i4.Future<void> saveGoal(_i11.SavingsGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#saveGoal, [goal]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i11.SavingsGoal>> watchActiveGoals() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveGoals, []),
            returnValue: _i4.Stream<List<_i11.SavingsGoal>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i11.SavingsGoal>>.empty(),
          )
          as _i4.Stream<List<_i11.SavingsGoal>>);

  @override
  _i4.Future<void> addContribution(_i12.GoalContribution? contribution) =>
      (super.noSuchMethod(
            Invocation.method(#addContribution, [contribution]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i12.GoalContribution>> watchContributions(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#watchContributions, [goalId]),
            returnValue: _i4.Stream<List<_i12.GoalContribution>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i12.GoalContribution>>.empty(),
          )
          as _i4.Stream<List<_i12.GoalContribution>>);
}

/// A class which mocks [IExchangeRateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExchangeRateRepository extends _i1.Mock
    implements _i13.IExchangeRateRepository {
  @override
  _i4.Future<void> save(_i14.ExchangeRate? rate) =>
      (super.noSuchMethod(
            Invocation.method(#save, [rate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i14.ExchangeRate?> getRate({
    required _i15.CurrencyCode? baseCurrencyCode,
    required _i15.CurrencyCode? quoteCurrencyCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRate, [], {
              #baseCurrencyCode: baseCurrencyCode,
              #quoteCurrencyCode: quoteCurrencyCode,
            }),
            returnValue: _i4.Future<_i14.ExchangeRate?>.value(),
            returnValueForMissingStub: _i4.Future<_i14.ExchangeRate?>.value(),
          )
          as _i4.Future<_i14.ExchangeRate?>);

  @override
  _i4.Stream<List<_i14.ExchangeRate>> watchAllRates() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllRates, []),
            returnValue: _i4.Stream<List<_i14.ExchangeRate>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i14.ExchangeRate>>.empty(),
          )
          as _i4.Stream<List<_i14.ExchangeRate>>);
}

/// A class which mocks [ISyncPushGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncPushGateway extends _i1.Mock implements _i2.ISyncPushGateway {
  @override
  _i4.Future<_i2.PushResult> pushTransactions(
    List<_i5.Transaction>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pushTransactions, [transactions]),
            returnValue: _i4.Future<_i2.PushResult>.value(
              _FakePushResult_0(
                this,
                Invocation.method(#pushTransactions, [transactions]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PushResult>.value(
              _FakePushResult_0(
                this,
                Invocation.method(#pushTransactions, [transactions]),
              ),
            ),
          )
          as _i4.Future<_i2.PushResult>);
}

/// A class which mocks [ISyncPullGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncPullGateway extends _i1.Mock implements _i2.ISyncPullGateway {
  @override
  _i4.Future<_i2.PullResult> pullChanges({required DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#pullChanges, [], {#since: since}),
            returnValue: _i4.Future<_i2.PullResult>.value(
              _FakePullResult_1(
                this,
                Invocation.method(#pullChanges, [], {#since: since}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PullResult>.value(
              _FakePullResult_1(
                this,
                Invocation.method(#pullChanges, [], {#since: since}),
              ),
            ),
          )
          as _i4.Future<_i2.PullResult>);
}
