// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
  t.category_id,
  c.name AS category_name,
  c.icon AS category_icon,
  c.color_hex AS category_color_hex,
  t.currency,
  COALESCE(SUM(t.amount), 0)::numeric AS total_amount
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.is_deleted = FALSE
  AND t.type = 'expense'
  AND EXTRACT(MONTH FROM t.transacted_at) = $2::int
  AND EXTRACT(YEAR FROM t.transacted_at) = $3::int
GROUP BY t.category_id, c.name, c.icon, c.color_hex, t.currency
ORDER BY total_amount DESC, category_name ASC
`

type GetCategoryBreakdownParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

type GetCategoryBreakdownRow struct {
	CategoryID       pgtype.UUID    `json:"category_id"`
	CategoryName     pgtype.Text    `json:"category_name"`
	CategoryIcon     pgtype.Text    `json:"category_icon"`
	CategoryColorHex pgtype.Text    `json:"category_color_hex"`
	Currency         string         `json:"currency"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColorHex,
			&i.Currency,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTotals = `-- name: GetMonthlyTotals :many
SELECT
  t.currency,
  COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0)::numeric AS income_total,
  COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0)::numeric AS expense_total,
  COALESCE(
    SUM(
      CASE
        WHEN t.type = 'income' THEN t.amount
        WHEN t.type = 'expense' THEN -t.amount
        ELSE 0
      END
    ),
    0
  )::numeric AS net_total
FROM transactions t
WHERE t.user_id = $1
  AND t.is_deleted = FALSE
  AND EXTRACT(MONTH FROM t.transacted_at) = $2::int
  AND EXTRACT(YEAR FROM t.transacted_at) = $3::int
GROUP BY t.currency
ORDER BY t.currency ASC
`

type GetMonthlyTotalsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

type GetMonthlyTotalsRow struct {
	Currency     string         `json:"currency"`
	IncomeTotal  pgtype.Numeric `json:"income_total"`
	ExpenseTotal pgtype.Numeric `json:"expense_total"`
	NetTotal     pgtype.Numeric `json:"net_total"`
}

func (q *Queries) GetMonthlyTotals(ctx context.Context, arg GetMonthlyTotalsParams) ([]GetMonthlyTotalsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTotals, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTotalsRow
	for rows.Next() {
		var i GetMonthlyTotalsRow
		if err := rows.Scan(
			&i.Currency,
			&i.IncomeTotal,
			&i.ExpenseTotal,
			&i.NetTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrend = `-- name: GetMonthlyTrend :many
WITH bounds AS (
  SELECT
    make_date($2::int, $3::int, 1)::date AS month_start,
    GREATEST($4::int, 1) AS month_count
)
SELECT
  EXTRACT(YEAR FROM date_trunc('month', t.transacted_at))::int AS year,
  EXTRACT(MONTH FROM date_trunc('month', t.transacted_at))::int AS month,
  t.currency,
  COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0)::numeric AS income_total,
  COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0)::numeric AS expense_total,
  COALESCE(
    SUM(
      CASE
        WHEN t.type = 'income' THEN t.amount
        WHEN t.type = 'expense' THEN -t.amount
        ELSE 0
      END
    ),
    0
  )::numeric AS net_total
FROM transactions t
CROSS JOIN bounds b
WHERE t.user_id = $1::uuid
  AND t.is_deleted = FALSE
  AND t.transacted_at >= (b.month_start - ((b.month_count - 1) * INTERVAL '1 month'))
  AND t.transacted_at < (b.month_start + INTERVAL '1 month')
GROUP BY
  EXTRACT(YEAR FROM date_trunc('month', t.transacted_at)),
  EXTRACT(MONTH FROM date_trunc('month', t.transacted_at)),
  t.currency
ORDER BY year ASC, month ASC, t.currency ASC
`

type GetMonthlyTrendParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
	Month  int32       `json:"month"`
	Months int32       `json:"months"`
}

type GetMonthlyTrendRow struct {
	Year         int32          `json:"year"`
	Month        int32          `json:"month"`
	Currency     string         `json:"currency"`
	IncomeTotal  pgtype.Numeric `json:"income_total"`
	ExpenseTotal pgtype.Numeric `json:"expense_total"`
	NetTotal     pgtype.Numeric `json:"net_total"`
}

func (q *Queries) GetMonthlyTrend(ctx context.Context, arg GetMonthlyTrendParams) ([]GetMonthlyTrendRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrend,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.Months,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTrendRow
	for rows.Next() {
		var i GetMonthlyTrendRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Currency,
			&i.IncomeTotal,
			&i.ExpenseTotal,
			&i.NetTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
