// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBudgetSpent = `-- name: GetBudgetSpent :one
SELECT
  COALESCE(SUM(t.amount), 0)::numeric AS spent_amount
FROM transactions t
WHERE t.user_id = $1
  AND t.category_id = $2
  AND t.type = 'expense'
  AND t.is_deleted = FALSE
  AND t.transacted_at >= make_date($3::int, $4::int, 1)::timestamptz
  AND t.transacted_at < (
    make_date($3::int, $4::int, 1)::timestamptz + INTERVAL '1 month'
  )
`

type GetBudgetSpentParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Year       int32       `json:"year"`
	Month      int32       `json:"month"`
}

func (q *Queries) GetBudgetSpent(ctx context.Context, arg GetBudgetSpentParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBudgetSpent,
		arg.UserID,
		arg.CategoryID,
		arg.Year,
		arg.Month,
	)
	var spent_amount pgtype.Numeric
	err := row.Scan(&spent_amount)
	return spent_amount, err
}

const getBudgetsByUserMonth = `-- name: GetBudgetsByUserMonth :many
SELECT
  id,
  user_id,
  category_id,
  currency,
  amount,
  month,
  year,
  rollover
FROM budgets
WHERE user_id = $1
  AND month = $2
  AND year = $3
ORDER BY category_id ASC
`

type GetBudgetsByUserMonthParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

func (q *Queries) GetBudgetsByUserMonth(ctx context.Context, arg GetBudgetsByUserMonthParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByUserMonth, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Currency,
			&i.Amount,
			&i.Month,
			&i.Year,
			&i.Rollover,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (
  user_id,
  category_id,
  currency,
  amount,
  month,
  year,
  rollover
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, category_id, month, year)
DO UPDATE SET
  currency = EXCLUDED.currency,
  amount = EXCLUDED.amount,
  rollover = EXCLUDED.rollover
RETURNING
  id,
  user_id,
  category_id,
  currency,
  amount,
  month,
  year,
  rollover
`

type UpsertBudgetParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Currency   string         `json:"currency"`
	Amount     pgtype.Numeric `json:"amount"`
	Month      int32          `json:"month"`
	Year       int32          `json:"year"`
	Rollover   pgtype.Bool    `json:"rollover"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Currency,
		arg.Amount,
		arg.Month,
		arg.Year,
		arg.Rollover,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Currency,
		&i.Amount,
		&i.Month,
		&i.Year,
		&i.Rollover,
	)
	return i, err
}
