// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserCategory = `-- name: CreateUserCategory :one
INSERT INTO categories (user_id, name, icon, color_hex, type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, icon, color_hex, type
`

type CreateUserCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Icon     string      `json:"icon"`
	ColorHex string      `json:"color_hex"`
	Type     string      `json:"type"`
}

func (q *Queries) CreateUserCategory(ctx context.Context, arg CreateUserCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createUserCategory, arg.UserID, arg.Name, arg.Icon, arg.ColorHex, arg.Type)
	var i Category
	err := row.Scan(&i.ID, &i.UserID, &i.Name, &i.Icon, &i.ColorHex, &i.Type)
	return i, err
}

const deleteUserCategory = `-- name: DeleteUserCategory :exec
DELETE FROM categories
WHERE id = $1
  AND user_id = $2
`

type DeleteUserCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserCategory(ctx context.Context, arg DeleteUserCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteUserCategory, arg.ID, arg.UserID)
	return err
}

const getSystemCategories = `-- name: GetSystemCategories :many
SELECT id, user_id, name, icon, color_hex, type
FROM categories
WHERE user_id IS NULL
ORDER BY name ASC
`

func (q *Queries) GetSystemCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getSystemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.Icon, &i.ColorHex, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategories = `-- name: GetUserCategories :many
SELECT id, user_id, name, icon, color_hex, type
FROM categories
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetUserCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name, &i.Icon, &i.ColorHex, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserCategory = `-- name: UpdateUserCategory :exec
UPDATE categories
SET name = $3,
    icon = $4,
    color_hex = $5,
    type = $6
WHERE id = $1
  AND user_id = $2
`

type UpdateUserCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Icon     string      `json:"icon"`
	ColorHex string      `json:"color_hex"`
	Type     string      `json:"type"`
}

func (q *Queries) UpdateUserCategory(ctx context.Context, arg UpdateUserCategoryParams) error {
	_, err := q.db.Exec(ctx, updateUserCategory, arg.ID, arg.UserID, arg.Name, arg.Icon, arg.ColorHex, arg.Type)
	return err
}

