// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllRatesForUser = `-- name: GetAllRatesForUser :many
SELECT
  id,
  user_id,
  from_currency,
  to_currency,
  rate,
  source,
  valid_at
FROM exchange_rates
WHERE user_id = $1
ORDER BY valid_at DESC, from_currency ASC, to_currency ASC
`

func (q *Queries) GetAllRatesForUser(ctx context.Context, userID pgtype.UUID) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, getAllRatesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRate
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Rate,
			&i.Source,
			&i.ValidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestRateForPair = `-- name: GetLatestRateForPair :one
SELECT
  id,
  user_id,
  from_currency,
  to_currency,
  rate,
  source,
  valid_at
FROM exchange_rates
WHERE user_id = $1
  AND from_currency = $2
  AND to_currency = $3
ORDER BY valid_at DESC
LIMIT 1
`

type GetLatestRateForPairParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	FromCurrency string      `json:"from_currency"`
	ToCurrency   string      `json:"to_currency"`
}

func (q *Queries) GetLatestRateForPair(ctx context.Context, arg GetLatestRateForPairParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestRateForPair, arg.UserID, arg.FromCurrency, arg.ToCurrency)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Source,
		&i.ValidAt,
	)
	return i, err
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :one
WITH updated AS (
  UPDATE exchange_rates
  SET rate = $1::numeric
  WHERE user_id = $2::uuid
    AND from_currency = $3::text
    AND to_currency = $4::text
    AND source = $5::text
    AND valid_at = $6::timestamptz
  RETURNING
    id,
    user_id,
    from_currency,
    to_currency,
    rate,
    source,
    valid_at
),
inserted AS (
  INSERT INTO exchange_rates (
    user_id,
    from_currency,
    to_currency,
    rate,
    source,
    valid_at
  )
  SELECT
    $2::uuid,
    $3::text,
    $4::text,
    $1::numeric,
    $5::text,
    $6::timestamptz
  WHERE NOT EXISTS (SELECT 1 FROM updated)
  RETURNING
    id,
    user_id,
    from_currency,
    to_currency,
    rate,
    source,
    valid_at
)
SELECT id, user_id, from_currency, to_currency, rate, source, valid_at FROM updated
UNION ALL
SELECT id, user_id, from_currency, to_currency, rate, source, valid_at FROM inserted
LIMIT 1
`

type UpsertExchangeRateParams struct {
	Rate         pgtype.Numeric     `json:"rate"`
	UserID       pgtype.UUID        `json:"user_id"`
	FromCurrency string             `json:"from_currency"`
	ToCurrency   string             `json:"to_currency"`
	Source       string             `json:"source"`
	ValidAt      pgtype.Timestamptz `json:"valid_at"`
}

type UpsertExchangeRateRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FromCurrency string             `json:"from_currency"`
	ToCurrency   string             `json:"to_currency"`
	Rate         pgtype.Numeric     `json:"rate"`
	Source       string             `json:"source"`
	ValidAt      pgtype.Timestamptz `json:"valid_at"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (UpsertExchangeRateRow, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRate,
		arg.Rate,
		arg.UserID,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Source,
		arg.ValidAt,
	)
	var i UpsertExchangeRateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Source,
		&i.ValidAt,
	)
	return i, err
}
