// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO savings_goals (
  user_id,
  name,
  emoji,
  goal_type,
  target_amount,
  currency,
  saved_amount,
  required_monthly,
  deadline,
  priority,
  is_completed
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
  id,
  user_id,
  name,
  emoji,
  goal_type,
  target_amount,
  currency,
  saved_amount,
  required_monthly,
  deadline,
  priority,
  is_completed,
  created_at
`

type CreateGoalParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Emoji           pgtype.Text    `json:"emoji"`
	GoalType        pgtype.Text    `json:"goal_type"`
	TargetAmount    pgtype.Numeric `json:"target_amount"`
	Currency        string         `json:"currency"`
	SavedAmount     pgtype.Numeric `json:"saved_amount"`
	RequiredMonthly pgtype.Numeric `json:"required_monthly"`
	Deadline        pgtype.Date    `json:"deadline"`
	Priority        pgtype.Int4    `json:"priority"`
	IsCompleted     pgtype.Bool    `json:"is_completed"`
}

type CreateGoalRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Emoji           pgtype.Text        `json:"emoji"`
	GoalType        pgtype.Text        `json:"goal_type"`
	TargetAmount    pgtype.Numeric     `json:"target_amount"`
	Currency        string             `json:"currency"`
	SavedAmount     pgtype.Numeric     `json:"saved_amount"`
	RequiredMonthly pgtype.Numeric     `json:"required_monthly"`
	Deadline        pgtype.Date        `json:"deadline"`
	Priority        pgtype.Int4        `json:"priority"`
	IsCompleted     pgtype.Bool        `json:"is_completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.GoalType,
		arg.TargetAmount,
		arg.Currency,
		arg.SavedAmount,
		arg.RequiredMonthly,
		arg.Deadline,
		arg.Priority,
		arg.IsCompleted,
	)
	var i CreateGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.GoalType,
		&i.TargetAmount,
		&i.Currency,
		&i.SavedAmount,
		&i.RequiredMonthly,
		&i.Deadline,
		&i.Priority,
		&i.IsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const createGoalContribution = `-- name: CreateGoalContribution :one
INSERT INTO goal_contributions (
  goal_id,
  amount,
  currency,
  notes,
  contributed_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
  id,
  goal_id,
  amount,
  currency,
  notes,
  contributed_at
`

type CreateGoalContributionParams struct {
	GoalID        pgtype.UUID        `json:"goal_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	Notes         pgtype.Text        `json:"notes"`
	ContributedAt pgtype.Timestamptz `json:"contributed_at"`
}

func (q *Queries) CreateGoalContribution(ctx context.Context, arg CreateGoalContributionParams) (GoalContribution, error) {
	row := q.db.QueryRow(ctx, createGoalContribution,
		arg.GoalID,
		arg.Amount,
		arg.Currency,
		arg.Notes,
		arg.ContributedAt,
	)
	var i GoalContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.ContributedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM savings_goals
WHERE id = $1
  AND user_id = $2
`

type DeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getContributionsByGoal = `-- name: GetContributionsByGoal :many
SELECT gc.id, gc.goal_id, gc.amount, gc.currency, gc.notes, gc.contributed_at
FROM goal_contributions gc
INNER JOIN savings_goals sg ON sg.id = gc.goal_id
WHERE gc.goal_id = $1
  AND sg.user_id = $2
ORDER BY gc.contributed_at DESC
`

type GetContributionsByGoalParams struct {
	GoalID pgtype.UUID `json:"goal_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetContributionsByGoal(ctx context.Context, arg GetContributionsByGoalParams) ([]GoalContribution, error) {
	rows, err := q.db.Query(ctx, getContributionsByGoal, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalContribution
	for rows.Next() {
		var i GoalContribution
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Amount,
			&i.Currency,
			&i.Notes,
			&i.ContributedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT
  id,
  user_id,
  name,
  emoji,
  goal_type,
  target_amount,
  currency,
  saved_amount,
  required_monthly,
  deadline,
  priority,
  is_completed,
  created_at
FROM savings_goals
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetGoalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetGoalByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Emoji           pgtype.Text        `json:"emoji"`
	GoalType        pgtype.Text        `json:"goal_type"`
	TargetAmount    pgtype.Numeric     `json:"target_amount"`
	Currency        string             `json:"currency"`
	SavedAmount     pgtype.Numeric     `json:"saved_amount"`
	RequiredMonthly pgtype.Numeric     `json:"required_monthly"`
	Deadline        pgtype.Date        `json:"deadline"`
	Priority        pgtype.Int4        `json:"priority"`
	IsCompleted     pgtype.Bool        `json:"is_completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (GetGoalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoalByID, arg.ID, arg.UserID)
	var i GetGoalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.GoalType,
		&i.TargetAmount,
		&i.Currency,
		&i.SavedAmount,
		&i.RequiredMonthly,
		&i.Deadline,
		&i.Priority,
		&i.IsCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalsByUser = `-- name: GetGoalsByUser :many
SELECT
  id,
  user_id,
  name,
  emoji,
  goal_type,
  target_amount,
  currency,
  saved_amount,
  required_monthly,
  deadline,
  priority,
  is_completed,
  created_at
FROM savings_goals
WHERE user_id = $1
ORDER BY priority ASC, created_at DESC
`

type GetGoalsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Emoji           pgtype.Text        `json:"emoji"`
	GoalType        pgtype.Text        `json:"goal_type"`
	TargetAmount    pgtype.Numeric     `json:"target_amount"`
	Currency        string             `json:"currency"`
	SavedAmount     pgtype.Numeric     `json:"saved_amount"`
	RequiredMonthly pgtype.Numeric     `json:"required_monthly"`
	Deadline        pgtype.Date        `json:"deadline"`
	Priority        pgtype.Int4        `json:"priority"`
	IsCompleted     pgtype.Bool        `json:"is_completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]GetGoalsByUserRow, error) {
	rows, err := q.db.Query(ctx, getGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGoalsByUserRow
	for rows.Next() {
		var i GetGoalsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Emoji,
			&i.GoalType,
			&i.TargetAmount,
			&i.Currency,
			&i.SavedAmount,
			&i.RequiredMonthly,
			&i.Deadline,
			&i.Priority,
			&i.IsCompleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE savings_goals
SET
  name = $3,
  emoji = $4,
  goal_type = $5,
  target_amount = $6,
  currency = $7,
  required_monthly = $8,
  deadline = $9,
  priority = $10,
  is_completed = $11
WHERE id = $1
  AND user_id = $2
`

type UpdateGoalParams struct {
	ID              pgtype.UUID    `json:"id"`
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Emoji           pgtype.Text    `json:"emoji"`
	GoalType        pgtype.Text    `json:"goal_type"`
	TargetAmount    pgtype.Numeric `json:"target_amount"`
	Currency        string         `json:"currency"`
	RequiredMonthly pgtype.Numeric `json:"required_monthly"`
	Deadline        pgtype.Date    `json:"deadline"`
	Priority        pgtype.Int4    `json:"priority"`
	IsCompleted     pgtype.Bool    `json:"is_completed"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.Exec(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.GoalType,
		arg.TargetAmount,
		arg.Currency,
		arg.RequiredMonthly,
		arg.Deadline,
		arg.Priority,
		arg.IsCompleted,
	)
	return err
}

const updateGoalSavedAmount = `-- name: UpdateGoalSavedAmount :exec
UPDATE savings_goals
SET saved_amount = $3
WHERE id = $1
  AND user_id = $2
`

type UpdateGoalSavedAmountParams struct {
	ID          pgtype.UUID    `json:"id"`
	UserID      pgtype.UUID    `json:"user_id"`
	SavedAmount pgtype.Numeric `json:"saved_amount"`
}

func (q *Queries) UpdateGoalSavedAmount(ctx context.Context, arg UpdateGoalSavedAmountParams) error {
	_, err := q.db.Exec(ctx, updateGoalSavedAmount, arg.ID, arg.UserID, arg.SavedAmount)
	return err
}
