// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID         pgtype.UUID    `json:"id"`
	UserID     pgtype.UUID    `json:"user_id"`
	CategoryID pgtype.UUID    `json:"category_id"`
	Currency   string         `json:"currency"`
	Amount     pgtype.Numeric `json:"amount"`
	Month      int32          `json:"month"`
	Year       int32          `json:"year"`
	Rollover   pgtype.Bool    `json:"rollover"`
}

type Category struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Icon     string      `json:"icon"`
	ColorHex string      `json:"color_hex"`
	Type     string      `json:"type"`
}

type ExchangeRate struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FromCurrency string             `json:"from_currency"`
	ToCurrency   string             `json:"to_currency"`
	Rate         pgtype.Numeric     `json:"rate"`
	Source       string             `json:"source"`
	ValidAt      pgtype.Timestamptz `json:"valid_at"`
}

type GoalContribution struct {
	ID            pgtype.UUID        `json:"id"`
	GoalID        pgtype.UUID        `json:"goal_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Currency      string             `json:"currency"`
	Notes         pgtype.Text        `json:"notes"`
	ContributedAt pgtype.Timestamptz `json:"contributed_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	DeviceID  string             `json:"device_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavingsGoal struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Emoji        pgtype.Text        `json:"emoji"`
	GoalType     pgtype.Text        `json:"goal_type"`
	TargetAmount pgtype.Numeric     `json:"target_amount"`
	Currency     string             `json:"currency"`
	SavedAmount  pgtype.Numeric     `json:"saved_amount"`
	Deadline     pgtype.Date        `json:"deadline"`
	Priority     pgtype.Int4        `json:"priority"`
	IsCompleted  pgtype.Bool        `json:"is_completed"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SyncLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Operation  string             `json:"operation"`
	Payload    []byte             `json:"payload"`
	SyncedAt   pgtype.Timestamptz `json:"synced_at"`
}

type Transaction struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	WalletID           pgtype.UUID        `json:"wallet_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Type               string             `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	Notes              pgtype.Text        `json:"notes"`
	Source             string             `json:"source"`
	TransactedAt       pgtype.Timestamptz `json:"transacted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IsDeleted          pgtype.Bool        `json:"is_deleted"`
	SyncID             pgtype.UUID        `json:"sync_id"`
	TransferToWalletID pgtype.UUID        `json:"transfer_to_wallet_id"`
	ExchangeRate       pgtype.Numeric     `json:"exchange_rate"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Name         string             `json:"name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Currency   string             `json:"currency"`
	WalletType string             `json:"wallet_type"`
	Balance    pgtype.Numeric     `json:"balance"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
