// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id,
  wallet_id,
  category_id,
  type,
  amount,
  currency,
  notes,
  source,
  transacted_at,
  sync_id,
  transfer_to_wallet_id,
  exchange_rate
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
  id,
  user_id,
  wallet_id,
  category_id,
  type,
  amount,
  currency,
  notes,
  source,
  transacted_at,
  created_at,
  is_deleted,
  sync_id,
  transfer_to_wallet_id,
  exchange_rate
`

type CreateTransactionParams struct {
	UserID             pgtype.UUID        `json:"user_id"`
	WalletID           pgtype.UUID        `json:"wallet_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Type               string             `json:"type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	Notes              pgtype.Text        `json:"notes"`
	Source             string             `json:"source"`
	TransactedAt       pgtype.Timestamptz `json:"transacted_at"`
	SyncID             pgtype.UUID        `json:"sync_id"`
	TransferToWalletID pgtype.UUID        `json:"transfer_to_wallet_id"`
	ExchangeRate       pgtype.Numeric     `json:"exchange_rate"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.WalletID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Currency,
		arg.Notes,
		arg.Source,
		arg.TransactedAt,
		arg.SyncID,
		arg.TransferToWalletID,
		arg.ExchangeRate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Source,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.SyncID,
		&i.TransferToWalletID,
		&i.ExchangeRate,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
  id,
  user_id,
  wallet_id,
  category_id,
  type,
  amount,
  currency,
  notes,
  source,
  transacted_at,
  created_at,
  is_deleted,
  sync_id,
  transfer_to_wallet_id,
  exchange_rate
FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Source,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.SyncID,
		&i.TransferToWalletID,
		&i.ExchangeRate,
	)
	return i, err
}

const getTransactionBySyncID = `-- name: GetTransactionBySyncID :one
SELECT
  id,
  user_id,
  wallet_id,
  category_id,
  type,
  amount,
  currency,
  notes,
  source,
  transacted_at,
  created_at,
  is_deleted,
  sync_id,
  transfer_to_wallet_id,
  exchange_rate
FROM transactions
WHERE sync_id = $1
LIMIT 1
`

func (q *Queries) GetTransactionBySyncID(ctx context.Context, syncID pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionBySyncID, syncID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Source,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.SyncID,
		&i.TransferToWalletID,
		&i.ExchangeRate,
	)
	return i, err
}

const getTransactionsByUser = `-- name: GetTransactionsByUser :many
SELECT
  id,
  user_id,
  wallet_id,
  category_id,
  type,
  amount,
  currency,
  notes,
  source,
  transacted_at,
  created_at,
  is_deleted,
  sync_id,
  transfer_to_wallet_id,
  exchange_rate
FROM transactions
WHERE user_id = $1
  AND is_deleted = FALSE
  AND ($2::uuid IS NULL OR wallet_id = $2::uuid)
  AND ($3::uuid IS NULL OR category_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR transacted_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR transacted_at <= $5::timestamptz)
  AND ($6::text IS NULL OR type = $6::text)
ORDER BY transacted_at DESC, created_at DESC
`

type GetTransactionsByUserParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.UUID        `json:"column_2"`
	Column3 pgtype.UUID        `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Column6 string             `json:"column_6"`
}

func (q *Queries) GetTransactionsByUser(ctx context.Context, arg GetTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Notes,
			&i.Source,
			&i.TransactedAt,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.SyncID,
			&i.TransferToWalletID,
			&i.ExchangeRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET is_deleted = TRUE
WHERE id = $1
  AND user_id = $2
`

type SoftDeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	return err
}
