// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, currency, wallet_type, balance, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, currency, wallet_type, balance, is_active, created_at
`

type CreateWalletParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	Name       string         `json:"name"`
	Currency   string         `json:"currency"`
	WalletType string         `json:"wallet_type"`
	Balance    pgtype.Numeric `json:"balance"`
	IsActive   pgtype.Bool    `json:"is_active"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserID,
		arg.Name,
		arg.Currency,
		arg.WalletType,
		arg.Balance,
		arg.IsActive,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.WalletType,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, user_id, name, currency, wallet_type, balance, is_active, created_at
FROM wallets
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWalletByID(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.WalletType,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletsByUser = `-- name: GetWalletsByUser :many
SELECT id, user_id, name, currency, wallet_type, balance, is_active, created_at
FROM wallets
WHERE user_id = $1
  AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetWalletsByUser(ctx context.Context, userID pgtype.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.WalletType,
			&i.Balance,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWallet = `-- name: SoftDeleteWallet :exec
UPDATE wallets
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) SoftDeleteWallet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteWallet, id)
	return err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET balance = $2
WHERE id = $1
`

type UpdateWalletBalanceParams struct {
	ID      pgtype.UUID    `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.ID, arg.Balance)
	return err
}

const updateWalletName = `-- name: UpdateWalletName :exec
UPDATE wallets
SET name = $2
WHERE id = $1
`

type UpdateWalletNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateWalletName(ctx context.Context, arg UpdateWalletNameParams) error {
	_, err := q.db.Exec(ctx, updateWalletName, arg.ID, arg.Name)
	return err
}

